### ISSUE TITLE
Feature request: Set the selected date by code

### ISSUE THREAD

**Issue by Ramfat** [nomanr/WeekCalendar#4]
Hi.
I would love it if there was a way to set the selected date of WeekCalendar programatically with a method, in a fashion similiar to the reset method. Maybe with a LocalDate or DateTime as parameter?

**Comment by nomanr** [comment]
Hmm that's a good feature. I'll add this feature over the weekend and then I'll close this issue.

**Comment by Ramfat** [comment]
Thank you very much! Both for the commitment to this project and also for your expedience in replying and resolving the matter.

**Comment by nomanr** [comment]
Use the version `1.0.5` and I added a new method `setSelectedDate(DateTime)`.
