### ISSUE TITLE
Another starting day

### ISSUE THREAD

**Issue by simongiesen** [nomanr/WeekCalendar#5]
Hi! Great work!

Would it be possible to start with a day of choice and display seven further days?

**Comment by nomanr** [comment]
Hey there,
This feature does't exists in current version yet, I'll add it sometimes later.

**Comment by simongiesen** [comment]
Fine! Perhaps I can fork it and add it, let's see

**Comment by nomanr** [comment]
Sure you can fork it and play with it :) 
I added the feature you requested. Use the version `1.0.6` and `setStartDate(DateTime )` method.
Glad my library helped you in some way.
Happy coding :)

**Comment by simongiesen** [comment]
Thanks !!!!!! All my best wishes from Germany!
