### ISSUE TITLE
java.lang.RuntimeException: Fragment is not currently in the FragmentManager

### ISSUE THREAD

**Issue by Ramfat** [nomanr/WeekCalendar#7]
Hi.

After entering the activity containing the view for the first time, all methods (reset, setSelected, etc) work as they should, but after leaving the activty (i.e activity is finished) and then opening same activity again (new instance) and using WeekCalendar methods the following RuntimeException is thrown: 

Unable to start activity <ACTIVITY>: java.lang.RuntimeException: Could not dispatch event: class noman.weekcalendar.eventbus.Event$ResetEvent to handler [EventHandler public void noman.weekcalendar.view.WeekPager.reset(noman.weekcalendar.eventbus.Event$ResetEvent)]: Fragment WeekFragment{3a871760} is not currently in the FragmentManager

Any idea how to solve this? 
Thanks in advance.

**Comment by nomanr** [comment]
https://github.com/nomanr/WeekCalendar/issues/8

**Comment by michel-t-86** [comment]
This is a memory leak issue. 

When the activity is destroyed, somehow the WeekPager of the WeekCalendar view remains in memory.

When a new activity is created and a call is made to a fresh WeekCalendar, the BusProvider dispatches the event to both the leaked WeekPager and the new WeekPager.
The event will work fine for the new WeekPager but will fail for the old one.

I don't know enough about Views lifecycle to fix it but I've place a temporary hack in WeekPager:

`
    private void initPager(DateTime dateTime) {
        pos = NUM_OF_PAGES / 2;
        adapter = new PagerAdapter(getContext(), ((AppCompatActivity) getContext())
                .getSupportFragmentManager(), dateTime, typedArray);
        try {
            setAdapter(adapter);
            addOnPageChangeListener(new ViewPager
                    .SimpleOnPageChangeListener() {
                @Override
                public void onPageSelected(int position) {
                    if (!check)
                        if (position < pos)
                            adapter.swipeBack();
                        else if (position > pos)
                            adapter.swipeForward();
                    pos = position;
                    check = false;

                }

            });
            setOverScrollMode(OVER_SCROLL_NEVER);
            setCurrentItem(pos);
            if (typedArray != null)
                setBackgroundColor(typedArray.getColor(R.styleable.WeekCalendar_daysBackgroundColor,
                        ContextCompat.getColor(getContext(), R.color.colorPrimary)));
            if (WeekFragment.selectedDateTime == null)
                WeekFragment.selectedDateTime = new DateTime();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
`
